"""Plot the saved 21-day block-bootstrap Sharpe intervals used in the report.

The robustness results are stored in results/tables/sharpe_bootstrap.csv and are
regenerated by scripts/run_part_b.py from the committed OOS fund-return panel.
This helper is kept as a lightweight way to redraw the report figure without
rerunning the full data/sentiment pipeline.
"""
from __future__ import annotations
import pathlib, sys
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd

ROOT=pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0,str(ROOT))
from src.plotstyle import fundx_theme, PALETTE, save_fig

LABELS={
    'combined_risk_parity':'Combined Risk Parity',
    'combined_max_sharpe':'Combined Max Sharpe',
    'combined_equal_weight':'Combined Equal Weight',
    'equity_equal_weight':'Equity Equal Weight',
    'equity_max_sharpe':'Equity Max Sharpe',
    'equity_max_sharpe_tilt_finvader':'Equity Max Sharpe + Fin-VADER',
}

def main():
    fundx_theme()
    df=pd.read_csv(ROOT/'results/tables/sharpe_bootstrap.csv',index_col=0)
    df['label']=[LABELS.get(i,i) for i in df.index]
    df=df.sort_values('sharpe')
    y=range(len(df))
    lo=df['sharpe']-df['ci_5pct']; hi=df['ci_95pct']-df['sharpe']
    fig,ax=plt.subplots(figsize=(9,4.4))
    ax.errorbar(df['sharpe'],list(y),xerr=[lo,hi],fmt='o',capsize=4,
                color=PALETTE['navy'],ecolor=PALETTE['steel'])
    ax.axvline(0,color=PALETTE['coral'],lw=1,ls='--')
    ax.set_yticks(list(y),df['label'])
    ax.set_xlabel('Annualised Sharpe ratio')
    ax.set_title('Sharpe uncertainty: 90% block-bootstrap intervals (21-day blocks, B=2,000)')
    ax.grid(axis='y',visible=False)
    fig.tight_layout()
    save_fig(fig,ROOT/'results/figures/sharpe_bootstrap_ci.png',
             'OOS 2021-01-04 to 2023-12-29 | 90% intervals')

if __name__=='__main__':
    main()
